src/apps/usuarios/urls.py
from django.urls import path 

from . import views  # Esta url no viene por defecto con django cuando creamos una nueva app, entonces la tuve que crear yo.

app_name = "usuarios"

urlpatterns = [
	# path('listaru/', views.listar_usuarios, name= "listar"),
	path('listaru/', views.Listar.as_view(), name="listar"),
	path('Nuevo/', views.nuevo_amigo, name="nuevo"),
]

src/encuesta/urls.py
from django.contrib.auth import views as auth_views
from django.contrib      import admin
from django.urls         import path, include   # Nota: para iniciar una nueva aplicacion tengo que usar el comando: 
                                                # django-admin startapp y el nombre de la app sin comillas

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name= 'irinicio'), # Esta url se encuntra en la carpeta de encustas 'principal' 
                                              # que ahi es donde van todas las configuraciones del proyecto
                                              # y esta url esta redirigida a la carpeta templantes donde esta el archivo inicio.html 

    path('Usuarios/', include('apps.usuarios.urls')), # Usuarios url de la aplicacion... 

    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),

    path('logout/', auth_views.logout_then_login, name="logout") # Esto ultimos dos tienen al parecer sus propias views importadas 
                                                                    # de otras clase o nose como decirlo bien... tengo que seguir.
]

src/apps/user/models.py
from django.db                  import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser): 
	apodo = models.CharField(max_length=22, null=True, blank=True)
	fecha_de_nacimiento = models.DateField(null=True,blank=True)
	direccion = models.CharField(max_length=255, null=True, blank=True)

	class Meta: 
		db_table = 'user' 

src/apps/usuarios/models.py
from django.db import models

# Create your models here.


class Usuarios(models.Model): 
	nombre = models.CharField(max_length=255)
	apellido = models.CharField(max_length=255)

	class Meta: 
		db_table = 'usuarios'

	def __str__(self): 
		return self.nombre

src/apps/usuarios/forms.py
from django import forms


from .models import Usuarios

class AmigoForm(forms.ModelForm): 
	class Meta:
		model = Usuarios
		fields = ["nombre", "apellido"]

src/apps/user/views.py
from django.shortcuts import render

# Create your views here.

src/apps/usuarios/views.py
from django.shortcuts 				import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins 	import LoginRequiredMixin
from django.views.generic 			import ListView
from .models 						import Usuarios
from .forms 						import AmigoForm
# Create your views here.
"""
def listar_usuarios(request): 
	template_name = "usuarios/listarusuarios.html"
	lista_de_usuarios = Usuarios.objects.all()
	ctx = {
		'usuarios' : lista_de_usuarios
	}
	return render(request, template_name, ctx)
"""



def nuevo_amigo(request): 
	template_name = "usuarios/nuevo.html"
	ctx = {
		'form': AmigoForm()
	}
	return render(request, template_name, ctx)


class Listar(LoginRequiredMixin, ListView): 
	template_name = "usuarios/listarusuarios.html" # Seguir despues, tiene un error... video Vistas basadas en funciones
													# y en clases--- 10: 00
	model = Usuarios
	
	context_object_name = 'usuarios'

	def get_queryset(self): 
		if self.request.user.is_superuser: 
			return Usuarios.objects.all()
		

		return Usuarios.objects.filter(nombre="Belen")

	"""
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["color"] = "amarillo"
		return context
	"""

src/encuesta/views.py
from django.contrib.auth.models import User
from django.shortcuts 			import render

def inicio(request): 
	template_name = "inicio.html"
	ctx = {

	}
	return render(request, template_name, ctx)

src/templates/base/base.html
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Trivia: Chaco</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="src/templates/css/estilos.css">

    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>

  <body>

    <header>
      <div class="bg-dark collapse" id="navbarHeader" style="">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">Informacion del Sitio</h4>
              <p class="text-muted">Este sitio fue desarrollado en el Informatorio Chaco 2021, por la Comision 4.Nombre de los participantes: Ivan Braslavsky Beveraggi, Agustin Muchutti, Alderete Emanuel, Gonzalez Olarte Carlos Samael, Rataric Lautaro.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Opciones</h4>
              <ul class="list-unstyled">
                {% if user.is_authenticated %}
                  <li><a href="{% url 'logout' %}" class="text-white">Cerrar Sesion</a></li>
                  <li><a href="{% url 'usuarios:listar' %}" class="text-white">Lista de Usuarios</a></li>
                  <li><a href="#" class="text-white">Compartir</a></li>
                  <li><a href="#" class="text-white">Jugar</a></li>
                {% else %}
                  <li><a href="{% url 'login' %}" class="text-white">Iniciar Sesion</a></li>
                {% endif %}
               
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="{% url 'irinicio' %}" class="navbar-brand d-flex align-items-center">
            
            <strong>Inicio</strong>
          </a>
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Bienvenidos a la Trivia Chaco</h1>
          <p class="lead text-muted">Trivia Chaco, se trata de un juego con una seria de preguntas para jugar y divertirte con tus amigos.</p>

          {% if not user.is_authenticated %}
            <p>
            <a href="{% url 'login' %}" class="btn btn-primary my-2">Iniciar Sesion</a>
            <!--<a href="#" class="btn btn-secondary my-2">Secondary action</a>>--> 
          </p>
          {% endif %}
          
        </div>
      </section>

      <!-- -->
      <center>
        <h3>
          Este Juego de entretenimiento consiste en una serie de preguntas y respuestas relacionadas a la provincia del Chaco. 
        </h3>
      </center>
        
      {% block contenido %}
        
      {% endblock contenido %}

    </main>

   
      <footer class="text-muted">
        <div class="container">
          <p class="float-right">
            <a href="#">Ir Arriba</a>
          </p>
          <p>Juego Trivia Chaco, Desarrollado por el Informatorio Chaco 2021, por la Comision 4. Agredecimiento oficial a nuestro profesor Lucas Ibañez.</p>
        </div> 
      </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  

<svg xmlns="http://www.w3.org/2000/svg" width="348" height="225" viewBox="0 0 348 225" preserveAspectRatio="none" style="display: none; visibility: hidden; position: absolute; top: -100%; left: -100%;"><defs><style type="text/css"></style></defs><text x="0" y="17" style="font-weight:bold;font-size:17pt;font-family:Arial, Helvetica, Open Sans, sans-serif">Thumbnail</text></svg><iframe src="https://www.ciuvo.com/ciuvo/globalstorage?version=2.1.3" style="position: absolute; width: 1px; height: 1px; left: -9999px;"></iframe></body></html>

src/templates/inicio.html
{% extends "base/base.html" %}

{% block contenido %}
  <center>
        <h2>
          Abarca temas tales como:
        </h2>
      </center>
  <section>
        <div class="container-all">
          <h2>1 - Cultura y Arte:</h2>
          <img src="https://www.google.com/url?sa=iurl=https%3A%2F%2Fwww.todo-argentina.net%2Fgeografia%2Fprovincias%2Fchaco%2Fturismo.htmlpsig=AOvVaw0yrJZzNkAZEzaWFat8CwpTust=1630063169065000source=imagescd=vfeved=0CAsQjRxqFwoTCPDGjdXIzvICFQAAAAAdAAAAABAD" width="300" height="300">
        </div>

         
  </section>

   <section>
      <center>
        <p>
          <h3>
            Por cada pregunta respondida se le sumara su respectivo punto y al final del juego se les dara un resultado final con su respectivo puntaje, eso dependera si ha respondido bien a todas las preguntas que esten en el cuestionario en curso.
          </h3>
        </p>
      </center>

      <center>
        <p>
          <h2>
            ¿Como es la modalidad del juego?
          </h2>
        </p>
      </center>
        <div>
        <center>
          <p>
            <h2>
              - La modalidad del juego es de multiple choice, donde se le presentara una pregunta con dichas opciones de las cuales una o mas de una seria la respuesta correcta.
            </h2>
          </p>
        </center>
      </div>
    </section>
  
{% endblock contenido %}

src/templates/login.html
{% extends "base/base.html" %}


{% block contenido %}
	<div class="loginnn">
		<div class="container">
			<div class="row">
				<div class="col">
					<h1>Iniciar Sesion</h1>
					<form method="POST">{% csrf_token %}
						  <div class="form-group">
						    <label for="exampleInputEmail1">Nombre de Usuario</label>
						    <input type="text" class="form-control" id="username" name= "username" aria-describedby="emailHelp" placeholder="Ingrese nombre de usuario">
						  </div>
						  <div class="form-group">
						    <label for="exampleInputPassword1">Contraseña</label>
						    <input type="password" class="form-control" id="password" name= "password" placeholder="Ingrese contraseña">
						  </div>
						  <button type="submit" class="btn btn-primary">Iniciar Sesion</button>
					</form>
				</div>
			</div>
		</div>
	</div>
	
{% endblock contenido %}

src/templates/usuarios/listarusuarios.html
{% extends "base/base.html" %}

{% block contenido %}
	<div class="listarrr">
		<div class="container">

			<div class="row">
				<div class="col">
					<h2>Lista de Usuarios</h2>
				</div>
			</div>

			<div class="row" style="padding:10px;">
				<div class="col">
					<a href="{% url 'usuarios:nuevo' %}" class="btn btn-success" style="float:right;">Nuevo Amigo</a>
				</div>
			</div>

			<div class="row">
				<div class="col">				
					<table class="table">
					  <thead>
					    <tr>
					      <th scope="col">Nombre</th>
					      <th scope="col">Apellido</th>
					    </tr>
					  </thead>
					  <tbody>
					  	{% for a in object_list %}
						    <tr>
						      <td>{{a.nombre}}</td>
						      <td>{{a.apellido}}</td>
						    </tr>
						{% empty %}
							<tr>
								<td>No se encontraron resultados</td>
							</tr>
						{% endfor %}
					  </tbody>
					</table>
			</div>
		</div>
	</div>
{% endblock contenido %}

src/templates/usuarios/nuevo.html
{% extends "base/base.html" %}

{% block contenido %}
	<div class="listarrr">
		<div class="container">

			<div class="row">
				<div class="col">
					<h1>Crear Amigo</h1>
				</div>
			</div>


			<div class="row">
				<div class="col">
					{{form.as_p}}
				</div>
			</div>
		</div>
	</div>


{% endblock contenido %}